name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
        with:
          version: latest
      - run: ruff check
      - run: ruff format --check
